import './globals.css';
import { Noto_Sans_KR } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const notoSansKr = Noto_Sans_KR({
	subsets: ['latin'],
	preload: true,
	weight: ['100', '400', '700', '900'],
});

export const metadata = {
	title: 'SAP 에코플랜터즈',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={notoSansKr.className}>{children}</body>
		</html>
	);
}
